events {
  worker_connections 1024;
}

http {
  # Headers de seguridad básicos
  map $sent_http_content_type $csp_header {
    default "default-src 'self'";
  }

  server {
    listen 8084;
    server_name dvwa-proxy;

    add_header X-Frame-Options "DENY";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Content-Security-Policy $csp_header;

    location / {
      proxy_pass http://dvwa:80;
    }
  }

  server {
    listen 8085;
    server_name webgoat-proxy;

    add_header X-Frame-Options "DENY";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";

    location / {
      proxy_pass http://webgoat:8080;
    }
  }

  server {
    listen 8086;
    server_name juice-proxy;

    add_header X-Frame-Options "DENY";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";

    location / {
      proxy_pass http://juice-shop:3000;
    }
  }
}
